name: Dewhurst Security Blog
description: "Information security blog for Dewhurst Security."
baseurl: https://blog.dewhurstsecurity.com

markdown: kramdown
highlighter: rouge
paginate: 15
excerpt_separator: https://github.com/jekyll/jekyll/issues/1401

plugins:
  - jekyll-sitemap
  - jekyll-paginate
